In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
customer = pd.read_csv("tesla_customers.csv")
orders = pd.read_csv("tesla_orders.csv")
revenue = pd.read_csv("tesla_revenue.csv")

In [7]:
customer.head()

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier
0,TES-C4356,David Patel,NaN,Shanghai,CN,DE,25-Aug-2022,Insider
1,TES-C10082,James Anderson,james.anderson842@example.com,Los Angeles,CA,US,08/12/2022,Referral Program
2,TES-C10444,Wei Smith,wei.smith692 at example.com,Austin,TX,UK,02-May-2022,Standard
3,TES-C9616,Sara Anderson,sara.anderson543 at example.com,Berlin,DE,CA,02-Oct-2022,Insider
4,TES-C5362,Ava Davis,ava.davis946@example.com,Austin,TX,DE,2024-04-30,Standard

In [9]:
orders.head()

,order_id,customer_id,order_date,product_category,quantity,unit_price_usd,order_status,payment_method
0,TES-O8315,TES-C2866,07-May-2023,Solar Panel Kit,1,19329.42,Delivered,Lease
1,TES-O9239,TES-C6442,2025-11-21,Powerwall,1,"$11,129.77",NaN,Lease
2,TES-O11506,TES-C6681,26-Feb-2023,Model 3,1,46001.21,Delivered,Credit Card
3,TES-O6287,TES-C10367,10-Jun-2023,Powerwall,1,9722.47,Cancelled,Credit Card
4,TES-O13071,TES-C4627,12-Apr-2025,Merchandise,5,290.03,Returned,Financing

In [10]:
revenue.head()

,revenue_id,order_id,payment_date,amount_paid_usd,payment_status,refund_amount_usd
0,TES-R17904,TES-O10172,12/23/2025,92516.94,Paid,0.0
1,TES-R15453,TES-O8040,2023-01-28,9563.37,Refunded,0.0
2,TES-R16155,TES-O11719,06-May-2025,89649.56,Paid,0.0
3,TES-R12673,TES-O6194,03-Feb-2024,226.18,Paid,0.0
4,TES-R12396,TES-O12080,21-Sep-2025,99376.81,Paid,0.0

In [11]:
print("customers",customer.shape)
print("orders",orders.shape)
print("revenue",revenue.shape)

customers (10166, 8)
orders (10166, 8)
revenue (9696, 6)

In [12]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10166 entries, 0 to 10165
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      10166 non-null  object
 1   customer_name    10166 non-null  object
 2   email            9353 non-null   object
 3   city             10166 non-null  object
 4   state_or_region  10166 non-null  object
 5   country          10166 non-null  object
 6   signup_date      10166 non-null  object
 7   membership_tier  9673 non-null   object
dtypes: object(8)
memory usage: 635.5+ KB

In [13]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10166 entries, 0 to 10165
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          10166 non-null  object
 1   customer_id       10166 non-null  object
 2   order_date        10166 non-null  object
 3   product_category  10166 non-null  object
 4   quantity          10166 non-null  int64
 5   unit_price_usd    10166 non-null  object
 6   order_status      9880 non-null   object
 7   payment_method    10166 non-null  object
dtypes: int64(1), object(7)
memory usage: 635.5+ KB

In [14]:
revenue.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9696 entries, 0 to 9695
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   revenue_id         9696 non-null   object
 1   order_id           9696 non-null   object
 2   payment_date       9696 non-null   object
 3   amount_paid_usd    9218 non-null   float64
 4   payment_status     9696 non-null   object
 5   refund_amount_usd  9696 non-null   float64
dtypes: float64(2), object(4)
memory usage: 454.6+ KB

Statistical Summary

In [16]:
customer.describe(include="all").T

                 count unique                       top  freq
customer_id      10166  10000                 TES-C1177     2
customer_name    10166   1943               Rahul Brown    27
email             9353   9144  noah.wang305@example.com     2
city             10166     30                   Fremont   949
state_or_region  10166      8                        CA  3014
country          10166      6                        CN  1744
signup_date      10166   4619                2023-05-08     9
membership_tier   9673      3          Referral Program  3254

In [17]:
orders.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,10166,10000,TES-O10131,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,10166,6248,TES-C9999,219,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_date,10166,3150,25-Nov-2024,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_category,10166,8,Supercharging Credits,1302,NaN,NaN,NaN,NaN,NaN,NaN,NaN
quantity,10166.0,NaN,NaN,NaN,1.453079,1.206847,-5.0,1.0,1.0,1.0,5.0
unit_price_usd,10166,9925,169.26,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_status,9880,5,Delivered,4175,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_method,10166,4,Cash,2611,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
revenue.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
revenue_id,9696,9696,TES-R13627,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_id,9696,9539,TES-O9999,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_date,9696,3124,25-Nov-2024,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
amount_paid_usd,9218.0,NaN,NaN,NaN,37405.591625,33766.204895,10.44,9004.5175,38023.735,75210.4925,99974.9
payment_status,9696,3,Paid,7670,NaN,NaN,NaN,NaN,NaN,NaN,NaN
refund_amount_usd,9696.0,NaN,NaN,NaN,5495.467035,18232.47219,0.0,0.0,0.0,0.0,99841.92

Missing Values

In [20]:
customer.isnull().sum()

customer_id          0
customer_name        0
email              813
city                 0
state_or_region      0
country              0
signup_date          0
membership_tier    493
dtype: int64

In [21]:
orders.isnull().sum()

order_id              0
customer_id           0
order_date            0
product_category      0
quantity              0
unit_price_usd        0
order_status        286
payment_method        0
dtype: int64

In [22]:
revenue.isnull().sum()

revenue_id             0
order_id               0
payment_date           0
amount_paid_usd      478
payment_status         0
refund_amount_usd      0
dtype: int64

Duplicates

In [23]:
customer.duplicated().sum()

np.int64(166)

In [25]:
orders.duplicated().sum()

np.int64(166)

In [26]:
revenue.duplicated().sum()

np.int64(0)

Datatype Check

In [27]:
customer.dtypes

customer_id        object
customer_name      object
email              object
city               object
state_or_region    object
country            object
signup_date        object
membership_tier    object
dtype: object

In [28]:
orders.dtypes

order_id            object
customer_id         object
order_date          object
product_category    object
quantity             int64
unit_price_usd      object
order_status        object
payment_method      object
dtype: object

In [29]:
revenue.dtypes

revenue_id            object
order_id              object
payment_date          object
amount_paid_usd      float64
payment_status        object
refund_amount_usd    float64
dtype: object

Customers dataset cleaning

In [35]:
customer_df = customer.copy()

In [40]:
customer_df.duplicated().sum()

np.int64(166)

In [38]:
customer_df[customer_df.duplicated()].head()

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier
1234,TES-C6776,sofia chen,sofia.chen820@example.com,Los Angeles,CA,DE,2023-01-12,Insider
1520,TES-C2052,Carlos Patel,carlos.patel427@example.com,Chicago,IL,CA,31-May-2021,Insider
1642,TES-C2894,Fatima Tanaka,fatima.tanaka962@example.com,Miami,FL,DE,2021-01-18,Standard
1648,TES-C7848,mohammed lee,mohammed.lee779@example.com,Shanghai,CN,DE,06/13/2025,Insider
1699,TES-C4024,Li Yamada,li.yamada651@example.com,Austin,TX,US,17-May-2022,Insider

In [44]:
customer_df=customer_df.drop_duplicates(
    subset="customer_id",
    keep="first",
)

In [45]:
customer_df.duplicated().sum()

np.int64(0)

In [47]:
customer_df.shape

(10000, 8)

Email inspection

In [50]:
customer_df['email'].dtype

dtype('O')

In [51]:
customer_df['email'].isnull().sum()

np.int64(798)

In [52]:
customer_df.head()

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier
0,TES-C4356,David Patel,NaN,Shanghai,CN,DE,25-Aug-2022,Insider
1,TES-C10082,James Anderson,james.anderson842@example.com,Los Angeles,CA,US,08/12/2022,Referral Program
2,TES-C10444,Wei Smith,wei.smith692 at example.com,Austin,TX,UK,02-May-2022,Standard
3,TES-C9616,Sara Anderson,sara.anderson543 at example.com,Berlin,DE,CA,02-Oct-2022,Insider
4,TES-C5362,Ava Davis,ava.davis946@example.com,Austin,TX,DE,2024-04-30,Standard

In [53]:
customer_df['email']=customer_df['email'].astype('string')

In [54]:
customer_df['email'].dtype

string[python]

In [ ]:
customer_df=(
    customer_df['email']
)

In [55]:
import re

# Restore customer_df and reset types safely
customer_df = customer.copy()
customer_df = customer_df.drop_duplicates(subset='customer_id', keep='first')
customer_df['email'] = customer_df['email'].astype('string')

# Replace 'at' (with any amount of surrounding whitespace) with '@'
# \b matches word boundaries to ensure we only replace the standalone word 'at'
customer_df['email'] = customer_df['email'].str.replace(r'\s*\bat\b\s*', '@', regex=True, flags=re.IGNORECASE).str.strip().str.lower()

# Display the cleaned head to verify the changes
display(customer_df.head())

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier
0,TES-C4356,David Patel,<NA>,Shanghai,CN,DE,25-Aug-2022,Insider
1,TES-C10082,James Anderson,james.anderson842@example.com,Los Angeles,CA,US,08/12/2022,Referral Program
2,TES-C10444,Wei Smith,wei.smith692@example.com,Austin,TX,UK,02-May-2022,Standard
3,TES-C9616,Sara Anderson,sara.anderson543@example.com,Berlin,DE,CA,02-Oct-2022,Insider
4,TES-C5362,Ava Davis,ava.davis946@example.com,Austin,TX,DE,2024-04-30,Standard

In [57]:
customer_df['email'].isnull().sum()

np.int64(798)

In [59]:
customer_df['email_missing']=customer_df['email'].isna()

In [60]:
customer_df['email_missing'].value_counts()

email_missing
False    9202
True      798
Name: count, dtype: int64

In [63]:
customer_df['membership_tier'].value_counts(dropna=False)

membership_tier
Referral Program    3200
Insider             3193
Standard            3122
Unknown              485
Name: count, dtype: int64

In [62]:
customer_df['membership_tier']=(
    customer_df['membership_tier'].fillna("Unknown").str.title()
)

In [67]:
customer_df['city'].value_counts()

city
Fremont          1048
Berlin           1031
Seattle          1026
Miami            1022
Chicago          1005
Austin            995
Los Angeles       992
Shanghai          978
New York          978
San Francisco     925
Name: count, dtype: int64

In [66]:
customer_df['city']=(
    customer_df['city'].astype(str).str.strip().str.title()
)

In [68]:
customer_df['state_or_region']=(
    customer_df['state_or_region'].astype(str).str.strip().str.title()
)

In [69]:
customer_df['country']=(
    customer_df['country'].astype(str).str.strip().str.title()
)

Date Cleaning

In [71]:
from os import error
#date cleaning
def parse(c):
  return pd.to_datetime(
      c,
      format='mixed',
      errors="coerce"
  )

In [72]:
customer_df['signup_date']=parse(customer_df['signup_date'])

In [73]:
customer_df['signup_date'].dtype

dtype('<M8[ns]')

In [74]:
customer_df['signup_date'].head(25)

0    2022-08-25
1    2022-08-12
2    2022-05-02
3    2022-10-02
4    2024-04-30
5    2025-10-11
6    2022-02-09
7    2022-07-06
8    2024-08-14
9    2023-03-13
10   2025-09-24
11   2023-02-09
12   2022-07-17
13   2023-11-09
14   2024-03-06
15   2022-01-08
16   2023-03-20
17   2021-06-25
18   2025-04-11
19   2021-03-28
20   2023-12-10
21   2023-11-18
22   2023-11-20
23   2024-06-21
24   2022-01-11
Name: signup_date, dtype: datetime64[ns]

In [75]:
customer['signup_date'].head(10)

0    25-Aug-2022
1     08/12/2022
2    02-May-2022
3    02-Oct-2022
4     2024-04-30
5     10/11/2025
6    09-Feb-2022
7     07/06/2022
8     2024-08-14
9    13-Mar-2023
Name: signup_date, dtype: object

In [76]:
customer_df.isnull().sum()

customer_id          0
customer_name        0
email              798
city                 0
state_or_region      0
country              0
signup_date          0
membership_tier      0
email_missing        0
dtype: int64

In [78]:
customer_df.sample(5)

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier,email_missing
9109,TES-C7459,Vivaan Garcia,vivaan.garcia742@example.com,Seattle,Wa,Us,2022-06-11,Standard,False
10106,TES-C3564,Olivia Smith,olivia.smith770@example.com,Seattle,Wa,Uk,2025-06-30,Referral Program,False
8750,TES-C10290,Sofia Lee,sofia.lee970@example.com,Los Angeles,Ca,Ca,2024-12-06,Insider,False
6424,TES-C1499,david wang,david.wang515@example.com,Miami,Fl,Ca,2022-10-29,Standard,False
333,TES-C3723,maria tanaka,maria.tanaka598@example.com,Seattle,Wa,Uk,2022-11-28,Insider,False

Orders data

In [79]:
orders_df=orders.copy()

In [82]:
orders_df.duplicated().sum()

np.int64(0)

In [81]:
orders_df=orders_df.drop_duplicates(
    subset="order_id",
    keep="first"
)

In [83]:
orders_df.shape

(10000, 8)

Quantity Inspection

In [84]:
orders_df['quantity'].dtype

dtype('int64')

In [85]:
orders_df['quantity'].describe()

count    10000.000000
mean         1.453600
std          1.206562
min         -5.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          5.000000
Name: quantity, dtype: float64

In [87]:
orders_df['quantity'].value_counts()

quantity
 1    7854
 5     556
 3     506
 2     450
 4     439
-1     159
-2      13
-3      10
-4       8
-5       5
Name: count, dtype: int64

In [88]:
orders_df[orders_df['quantity']<0]

,order_id,customer_id,order_date,product_category,quantity,unit_price_usd,order_status,payment_method
94,TES-O7939,TES-C9321,09-Mar-2023,Solar Panel Kit,-1,17997.39,Shipped,Lease
99,TES-O6745,TES-C5071,20-Aug-2023,Supercharging Credits,-1,97.8,Shipped,Credit Card
100,TES-O5426,TES-C5215,2024-05-15,Model X,-1,89344.94,Shipped,Financing
252,TES-O6992,TES-C1429,02/07/2025,Merchandise,-4,279.63,Delivered,Lease
273,TES-O12024,TES-C5507,2024-03-14,Supercharging Credits,-2,135.76,Delivered,Financing
...,...,...,...,...,...,...,...,...
10017,TES-O13698,TES-C7592,15-Dec-2025,Solar Panel Kit,-1,22210.81,Cancelled,Cash
10039,TES-O9870,TES-C7388,05/09/2023,Model 3,-1,"$41,680.89",Delivered,Credit Card
10045,TES-O5896,TES-C4358,07/13/2025,Powerwall,-1,"$10,328.74",Cancelled,Lease
10060,TES-O11336,TES-C7097,01-Dec-2025,Solar Panel Kit,-1,20188.47,Cancelled,Credit Card
10071,TES-O9551,TES-C10214,10/17/2025,Model S,-1,75297.21,Cancelled,Financing

In [89]:
orders_df['quantity']=(orders_df['quantity'].abs())

In [90]:
orders_df[orders_df['quantity']<0]

Empty DataFrame
Columns: [order_id, customer_id, order_date, product_category, quantity, unit_price_usd, order_status, payment_method]
Index: []

In [91]:
orders_df.head()

,order_id,customer_id,order_date,product_category,quantity,unit_price_usd,order_status,payment_method
0,TES-O8315,TES-C2866,07-May-2023,Solar Panel Kit,1,19329.42,Delivered,Lease
1,TES-O9239,TES-C6442,2025-11-21,Powerwall,1,"$11,129.77",NaN,Lease
2,TES-O11506,TES-C6681,26-Feb-2023,Model 3,1,46001.21,Delivered,Credit Card
3,TES-O6287,TES-C10367,10-Jun-2023,Powerwall,1,9722.47,Cancelled,Credit Card
4,TES-O13071,TES-C4627,12-Apr-2025,Merchandise,5,290.03,Returned,Financing

In [92]:
# Clean unit_price_usd column by removing '$' and ','
orders_df['unit_price_usd'] = orders_df['unit_price_usd'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)

# Convert the column to numeric float type
orders_df['unit_price_usd'] = pd.to_numeric(orders_df['unit_price_usd'], errors='coerce')

# Display the statistics and verify the conversion
display(orders_df['unit_price_usd'].describe())
display(orders_df.head())

count    10000.000000
mean     37236.241737
std      33751.741695
min         10.140000
25%        297.620000
50%      38065.610000
75%      54853.747500
max      99974.900000
Name: unit_price_usd, dtype: float64

,order_id,customer_id,order_date,product_category,quantity,unit_price_usd,order_status,payment_method
0,TES-O8315,TES-C2866,07-May-2023,Solar Panel Kit,1,19329.42,Delivered,Lease
1,TES-O9239,TES-C6442,2025-11-21,Powerwall,1,11129.77,NaN,Lease
2,TES-O11506,TES-C6681,26-Feb-2023,Model 3,1,46001.21,Delivered,Credit Card
3,TES-O6287,TES-C10367,10-Jun-2023,Powerwall,1,9722.47,Cancelled,Credit Card
4,TES-O13071,TES-C4627,12-Apr-2025,Merchandise,5,290.03,Returned,Financing

#Product Category

In [93]:
orders_df['product_category'].value_counts(dropna=False)

product_category
Model 3                  1279
Supercharging Credits    1279
Model S                  1252
Solar Panel Kit          1251
Model X                  1239
Model Y                  1236
Powerwall                1234
Merchandise              1230
Name: count, dtype: int64

In [94]:
orders_df['product_category']=(
    orders_df['product_category'].astype(str).str.strip().str.title()
)

In [98]:
orders_df['order_status'].value_counts(dropna=False)

order_status
Delivered    4103
Shipped      1437
Cancelled    1393
Returned     1392
Pending      1391
Unknown       284
Name: count, dtype: int64

In [97]:
orders_df['order_status']=(
    orders_df['order_status'].fillna("Unknown").str.title()
)

In [99]:
orders_df['payment_method'].value_counts(dropna=False)

payment_method
Cash           2571
Financing      2538
Lease          2520
Credit Card    2371
Name: count, dtype: int64

In [100]:
orders_df['payment_method']=(
    orders_df['payment_method'].astype(str).str.strip().str.title()
)

In [101]:
orders_df['order_date']=parse(orders_df['order_date'])

In [104]:
orders_df['order_date'].head(25)

0    2023-05-07
1    2025-11-21
2    2023-02-26
3    2023-06-10
4    2025-04-12
5    2024-09-20
6    2023-03-26
7    2023-02-19
8    2024-01-27
9    2025-07-09
10   2024-12-28
11   2024-07-13
12   2023-09-03
13   2023-02-01
14   2024-04-23
15   2024-07-04
16   2023-05-19
17   2024-07-19
18   2023-07-02
19   2025-02-15
20   2023-09-07
21   2025-02-09
22   2025-09-08
23   2025-08-19
24   2023-04-15
Name: order_date, dtype: datetime64[ns]

Check null values in orders table

In [105]:
# 1. Restore 'amount_paid_usd' by copying from original 'revenue' source and re-applying numeric cleaning
revenue_df['amount_paid_usd'] = revenue.loc[revenue_df.index, 'amount_paid_usd']

revenue_df['amount_paid_usd'] = (
    revenue_df['amount_paid_usd']
    .astype(str)
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
)
revenue_df['amount_paid_usd'] = pd.to_numeric(revenue_df['amount_paid_usd'], errors='coerce')

# 2. Correctly clean and parse 'payment_date'
revenue_df['payment_date'] = parse(revenue_df['payment_date'])

# 3. Check null values and display head to verify
display(revenue_df.isnull().sum())
display(revenue_df.head())

order_id            0
customer_id         0
order_date          0
product_category    0
quantity            0
unit_price_usd      0
order_status        0
payment_method      0
dtype: int64

#Revenue Data Cleaning

In [123]:
revenue_df=revenue.copy()

In [124]:
revenue_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9696 entries, 0 to 9695
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   revenue_id         9696 non-null   object
 1   order_id           9696 non-null   object
 2   payment_date       9696 non-null   object
 3   amount_paid_usd    9218 non-null   float64
 4   payment_status     9696 non-null   object
 5   refund_amount_usd  9696 non-null   float64
dtypes: float64(2), object(4)
memory usage: 454.6+ KB

In [125]:
revenue_df.dtypes

revenue_id            object
order_id              object
payment_date          object
amount_paid_usd      float64
payment_status        object
refund_amount_usd    float64
dtype: object

In [126]:
revenue_df.duplicated().sum()

np.int64(0)

In [127]:
#Remove duplicate records
revenue_df=revenue_df.drop_duplicates(
    subset="revenue_id",
    keep="first"
)

In [128]:
revenue_df.shape

(9696, 6)

Inspecting amount_paid_usd

In [129]:
revenue_df.describe()

       amount_paid_usd  refund_amount_usd
count      9218.000000        9696.000000
mean      37405.591625        5495.467035
std       33766.204895       18232.472190
min          10.440000           0.000000
25%        9004.517500           0.000000
50%       38023.735000           0.000000
75%       75210.492500           0.000000
max       99974.900000       99841.920000

In [130]:
revenue_df['amount_paid_usd'].isnull().sum()

np.int64(478)

In [131]:
revenue_df ["amount_paid_usd"] = (
revenue_df ["amount_paid_usd"]
.astype(str)
.str.replace("$","", regex=False)
.str.replace(",", "", regex=False))

revenue_df ["amount_paid_usd"] = pd.to_numeric(
revenue_df ["amount_paid_usd"],
errors="coerce")

In [132]:
revenue_df['refund_amount_usd'].dtype

dtype('float64')

In [133]:
revenue_df ["refund_amount_usd"] = (
revenue_df['refund_amount_usd'].astype(str)
.str.replace("$","", regex=False)
.str.replace(",", "", regex=False))

revenue_df ["refund_amount_usd"] = pd.to_numeric(
revenue_df ["refund_amount_usd"],
errors="coerce")

In [137]:
revenue_df['amount_paid_usd'].head(20)

0     92516.94
1      9563.37
2     89649.56
3       226.18
4     99376.81
5     16632.79
6     89700.87
7     46489.59
8     11550.62
9     40792.81
10      468.06
11    51560.79
12      914.15
13      336.00
14    10362.24
15      575.88
16    95919.27
17    21994.66
18         NaN
19      147.45
Name: amount_paid_usd, dtype: float64

In [135]:
revenue_df['payment_date']=parse(revenue_df['payment_date'])

In [136]:
revenue_df['payment_date'].head(20)

0    2025-12-23
1    2023-01-28
2    2025-05-06
3    2024-02-03
4    2025-09-21
5    2023-09-17
6    2025-04-09
7    2024-09-23
8    2023-02-19
9    2023-09-05
10   2025-06-28
11   2024-08-02
12   2023-04-06
13   2023-08-22
14   2025-02-16
15   2023-02-25
16   2025-03-04
17   2024-07-23
18   2023-01-21
19   2025-07-06
Name: payment_date, dtype: datetime64[ns]

In [138]:
revenue_df[revenue_df['amount_paid_usd'].isna()]

,revenue_id,order_id,payment_date,amount_paid_usd,payment_status,refund_amount_usd
18,TES-R13000,TES-O13540,2023-01-21,NaN,Paid,0.00
33,TES-R15913,TES-O9633,2023-03-09,NaN,Paid,0.00
56,TES-R12347,TES-O12408,2025-03-22,NaN,Refunded,0.00
74,TES-R9383,TES-O12483,2024-02-26,NaN,Pending,0.00
77,TES-R10242,TES-O6502,2025-02-16,NaN,Refunded,0.00
...,...,...,...,...,...,...
9617,TES-R14805,TES-O8490,2023-12-25,NaN,Paid,0.00
9619,TES-R11067,TES-O13845,2025-10-13,NaN,Paid,3552.24
9626,TES-R16111,TES-O6052,2025-06-02,NaN,Paid,121.10
9638,TES-R15889,TES-O9695,2023-11-02,NaN,Refunded,0.00
9655,TES-R13967,TES-O9031,2024-08-23,NaN,Paid,45411.99

In [139]:
# Calculate the expected total order value from orders_df
orders_df['total_order_value'] = orders_df['quantity'] * orders_df['unit_price_usd']

# Merge this expected value into revenue_df on order_id
revenue_df = revenue_df.merge(
    orders_df[['order_id', 'total_order_value']],
    on='order_id',
    how='left'
)

# Fill missing amount_paid_usd with total_order_value
missing_before = revenue_df['amount_paid_usd'].isna().sum()
revenue_df['amount_paid_usd'] = revenue_df['amount_paid_usd'].fillna(revenue_df['total_order_value'])
missing_after = revenue_df['amount_paid_usd'].isna().sum()

print(f"Missing amount_paid_usd values before: {missing_before}")
print(f"Missing amount_paid_usd values after filling from order values: {missing_after}")

# Drop the helper total_order_value column if desired
revenue_df = revenue_df.drop(columns=['total_order_value'])

display(revenue_df.head(10))

Missing amount_paid_usd values before: 478
Missing amount_paid_usd values after filling from order values: 0

,revenue_id,order_id,payment_date,amount_paid_usd,payment_status,refund_amount_usd
0,TES-R17904,TES-O10172,2025-12-23,92516.94,Paid,0.00
1,TES-R15453,TES-O8040,2023-01-28,9563.37,Refunded,0.00
2,TES-R16155,TES-O11719,2025-05-06,89649.56,Paid,0.00
3,TES-R12673,TES-O6194,2024-02-03,226.18,Paid,0.00
4,TES-R12396,TES-O12080,2025-09-21,99376.81,Paid,0.00
5,TES-R14970,TES-O13333,2023-09-17,16632.79,Paid,16632.79
6,TES-R9443,TES-O5287,2025-04-09,89700.87,Pending,0.00
7,TES-R9457,TES-O12131,2024-09-23,46489.59,Paid,10266.53
8,TES-R9007,TES-O13515,2023-02-19,11550.62,Paid,1207.91
9,TES-R11221,TES-O9473,2023-09-05,40792.81,Paid,0.00

In [140]:
revenue_df.isnull().sum()

revenue_id           0
order_id             0
payment_date         0
amount_paid_usd      0
payment_status       0
refund_amount_usd    0
dtype: int64